namespace ShippingSystem.Enums
{
    public enum ShipmentStatusEnum
    {
        Pending,
        InWarehouse,
        PickedUp,
        Returned,
        Exchanged,
        Delivered,
        Canceled,
        InReviewForPickup,
        InReviewForReturn,
        InReviewForDelivery,
        InReviewForCancellation,
        InReviewForExchange,
        WaitingForPickup,
        WaitingForReturn,
        WaitingForExchange,
        WaitingForDelivery,
        OutForDelivery,
        ReturningToWarehouse,
        ReturningToShipper,
        OnHold,
        FailedDelivery,
        Lost,
        Damaged
    }
}